### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'Notification'

### ISSUE THREAD

**Issue by pdonaire1** [benqo/python-dhl#4]
Making the example that python-dhl in README, I have this error:

```
>>> rate_response = service.rate_request(shipment)
No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/dhl/service.py", line 56, in rate_request
AttributeError: 'unicode' object has no attribute 'Notification'
```

Please I need your help.
Thanks.

**Comment by oxidworks** [comment]
I had the same error, it was because reply was not an object but a string, u"Unauthorized".

What kind of account is used for this? I did not get it running.

**Comment by Maestro1** [comment]
@oxidworks  did you manage to solve this??
